"""Add todos column to users, and also add created_at, updated_at to todos

Revision ID: 89daa4c28d48
Revises: 356794a9dcd2
Create Date: 2026-02-01 23:07:53.591695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89daa4c28d48'
down_revision: Union[str, Sequence[str], None] = '356794a9dcd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable to avoid SQLite non-constant default error
    op.add_column('todos', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('todos', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # Backfill existing rows with current timestamp
    op.execute("UPDATE todos SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.execute("UPDATE todos SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL")
    # Mark columns as non-null using a batch operation (SQLite will recreate table safely)
    with op.batch_alter_table('todos') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DateTime(), nullable=False)
        batch_op.alter_column('updated_at', existing_type=sa.DateTime(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'updated_at')
    op.drop_column('todos', 'created_at')
    # ### end Alembic commands ###
